import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <nav className="bg-black py-4 md:px-10 px-4">
          <Link href='/' className="flex items-center gap-1">
            <Image
              src="/chefhat.svg"
              alt="chef hat svg"
              width={40}
              height={40}
            />
            <span className="text-2xl font-bold text-white">Dishify</span>
          </Link>
        </nav>
        {children}
        <footer className="bg-black py-6 text-center">
          <span className="text-white">
            &copy; 2025 Dounhuward B. Caparas <br />
            All Rights Reserved.
          </span>
        </footer>
      </body>
    </html>
  );
}
